// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOOG5dJn2U9cMmJ_qPX6h0pToaopHL3ks',
    appId: '1:486260726670:web:83f7417d59691207a322df',
    messagingSenderId: '486260726670',
    projectId: 'fluttercoursework-1e3e6',
    authDomain: 'fluttercoursework-1e3e6.firebaseapp.com',
    storageBucket: 'fluttercoursework-1e3e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2NOr5Im1-VTh-J3cH2OMLaM1MVAcf1hs',
    appId: '1:486260726670:android:59e1fb903e38d84da322df',
    messagingSenderId: '486260726670',
    projectId: 'fluttercoursework-1e3e6',
    storageBucket: 'fluttercoursework-1e3e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOHiHSHrmIK7Wx9EX9u1VXIZSkOrP2rsw',
    appId: '1:486260726670:ios:dbea34dc19bbbf88a322df',
    messagingSenderId: '486260726670',
    projectId: 'fluttercoursework-1e3e6',
    storageBucket: 'fluttercoursework-1e3e6.appspot.com',
    iosBundleId: 'com.example.cwflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOHiHSHrmIK7Wx9EX9u1VXIZSkOrP2rsw',
    appId: '1:486260726670:ios:b48da7a87dcbca27a322df',
    messagingSenderId: '486260726670',
    projectId: 'fluttercoursework-1e3e6',
    storageBucket: 'fluttercoursework-1e3e6.appspot.com',
    iosBundleId: 'com.example.cwflutter.RunnerTests',
  );
}
